### PR TITLE
Remove not needed require from test package

### PR DESCRIPTION
**Pull request by danimtb**
I don't know how it worked in CI but this was failing during a `conan create` in my machine.

cc/ @Croydon

### CODE REVIEW

**Comment by Croydon** [comment]
But it is needed 🤔 

cppnanomsg is header only C++ wrapper, meaning object orientated wrapper around the C library nanomsg. It directly calls the nanomsg methods and can't work without it.

The reason I added it to test_package instead of the main conanfile.py is that the packaging would be kinda weird: the header-only packaging don't need settings, but nanomsg get's compiled and has settings therefore.

Not sure how this could play together well, so I decided to not make it a direct dependency and leave it to the users. The test_package should actually test something, so I included it as a test dependency.

Did I overthink that somehow?

And what is the error you got?

**Comment by danimtb** [comment]
So if cppnanomsg needs the dependency nanomsg, then the second should be a requirement of the first.

Being cppnanomsg a header only lib does not mean that Conan will clean the settings. Conan will apply settings when needed to all dependencies and consumers would have to specify a complete profile to install this "header only" package as usual.

Hope that makes sense :)

**Review by Croydon — APPROVED** [review]
LGTM, thanks!

I guess I did overthink that 😄

**Comment by danimtb** [comment]
No problem, here to help! 👍

**Pull request merged**
